name: Add issue to project
on:
  issues:
    type:
      - opened
      
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@36464acb844fc53b9b8b2401da68844f6b05ebb0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}

      - name: add to project
        env: 
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          ORGANIZATION: FenderLang
          PROJECT_NUMBER: 1
        uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/FenderLang/projects/1
          github-token: ${{ env.GITHUB_TOKEN }}
